spring:
  kafka:
    clientId: "local.resize.service.zipkin"
    producer:
      transactionIdPrefix: local-resize-service-
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: local.resize
    properties:
      clientId.app: "local.resize.service"
  profiles:
    include: kafka-avro, kafka-producer, kafka-consumer