---
# Manifest for deployments to PCF Dev
applications:
- name: config
  buildpack: https://github.com/cloudfoundry/java-buildpack.git#v4.5.2
  memory: 768M
  disk_quota: 256M
  host: config
  instances: 1
  stack: cflinuxfs2
  env:
    SPRING_PROFILES_ACTIVE: git-pcf
    JAVA_OPTS: '-Xmx512m'

services:
- git