spring:
  kafka:
    clientId: "local.user.service.zipkin"
    producer:
      transactionIdPrefix: local-user-service-
    properties:
      clientId.app: "local.user.service"
  profiles:
    include: kafka-producer