---
# Manifest for deployments to PCF Dev
applications:
- name: storage-service
  buildpack: https://github.com/cloudfoundry/java-buildpack.git#v4.5.2
  memory: 768M
  disk_quota: 256M
  host: storage-service
  instances: 1
  stack: cflinuxfs2
  env:
    JAVA_OPTS: '-Xmx512m'

services:
- config
- eureka
- rabbitmq
- mongodb-storage-service
