spring:
  kafka:
    clientId: "local.storage.service"
    producer:
      transactionIdPrefix: local-storage-service
    consumer:
      group-id: local.storage
      properties:
        # Use specific packages or * for all packages, cannot be combined together
        spring.json.trusted.packages: 'info.novatec.spring.showcase.user.message.v1.resource'
  profiles:
    include: kafka-producer, kafka-consumer