version: "3"
services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "identityserver"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "IdentityDb#1"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
