version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - mssql
    mssql:
        image: "microsoft/mssql-server-linux:2017-CU4"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "IdentityDb#1"
            ACCEPT_EULA: "Y"

