spring:
  kafka:
    clientId: "local.comment.service"
    producer:
      transactionIdPrefix: local-comment-service-
    consumer:
      group-id: local.comment
      properties:
        # Use specific packages or * for all packages, cannot be combined together
        spring.json.trusted.packages: 'info.novatec.spring.showcase.user.message.v1.resource,info.novatec.spring.showcase.image.message.v1.resource'
  profiles:
    include: kafka-producer, kafka-consumer