spring:
  kafka:
    clientId: "local.comment.service.zipkin"
    producer:
      transactionIdPrefix: local-comment-service-
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: local.comment
    properties:
      clientId.app: "local.comment.service"
  profiles:
    include: kafka-avro, kafka-producer, kafka-consumer